/*
 * For CSCI 451: Computational Biology
 * Fall Semester, 2017
 * As this is for an undergrad class, resuse is ill-advised.
 */
package homework5;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Samuel Shissler, Brendan Tracey, and John Trapp
 */
public class TheSuperAwesomeExtendedJPanelOfDoom extends javax.swing.JPanel {

    private File file;
    private ArrayList<String> dnaStrands;

    /**
     * Creates new form TheSuperAwesomeExtendedJPanelOfDoom
     */
    public TheSuperAwesomeExtendedJPanelOfDoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        jSplitPane2 = new javax.swing.JSplitPane();
        startButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(1000, 950));
        setMinimumSize(new java.awt.Dimension(1000, 950));
        setName(""); // NOI18N

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1000, 950));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1000, 950));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.setFileFilter(new FileNameExtensionFilter("TEXT FILES", "txt", "text", "*.txt"));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(jFileChooser1);

        inputTextArea.setEditable(false);
        inputTextArea.setColumns(20);
        inputTextArea.setRows(5);
        inputTextArea.setText("Please choose the .txt file above and select \"Open.\"");
        jScrollPane1.setViewportView(inputTextArea);

        jSplitPane1.setRightComponent(jScrollPane1);

        jTabbedPane1.addTab("Input", jSplitPane1);

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        startButton.setText("START Phylogeny Prediction");
        startButton.setEnabled(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jSplitPane2.setTopComponent(startButton);

        outputTextArea.setEditable(false);
        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        jScrollPane3.setViewportView(outputTextArea);

        jSplitPane2.setRightComponent(jScrollPane3);

        jTabbedPane1.addTab("Output", jSplitPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        file = jFileChooser1.getSelectedFile();
        dnaStrands = new ArrayList<>();

        try {
            Scanner sc = new Scanner(file);
            while (sc.hasNextLine()) {
                dnaStrands.add(sc.nextLine());
            }
            startButton.setEnabled(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TheSuperAwesomeExtendedJPanelOfDoom.class.getName()).log(Level.SEVERE, null, ex);
        }

        String tempString = "";
        for (String strand : dnaStrands) {
            tempString += strand;
            tempString += "\n";
        }
        inputTextArea.setText(tempString);
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        //Disable the button
        startButton.setEnabled(false);
        
        //Send of the data!
        PhylogenyPrediction predictorOMatic = new PhylogenyPrediction(dnaStrands);
        predictorOMatic.doTheStuffWithTheThings();

        //Print out the data
        outputTextArea.setText(predictorOMatic.printOutput());
        //TODO: Print out the tree
    }//GEN-LAST:event_startButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
